fix code coverage setting

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -26,11 +26,10 @@ script:
   - tox
   - |
     if [[ "$COVERAGE" == "true" ]]; then
-      pre-commit install
-      pre-commit run --all-files
+      python setup.py test --addopts --cov=src/
     fi
 after_success:
-  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
+  - if [[ "$COVERAGE" == "true" ]]; then codecov || echo "failed"; fi
 after_script:
   - travis-cleanup
 cache:
